# Generated by Django 3.1.3 on 2020-11-28 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thali_name', models.CharField(max_length=200)),
                ('kab_banaya', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='kyakhayega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitne_thali', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('thali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.menu')),
            ],
        ),
    ]
